import {
  Award,
  BadgeCheck,
  Bird,
  BookOpen,
  BookMarked,
  Brain,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  ClipboardList,
  Crown,
  Delete,
  Eraser,
  Feather,
  FileText,
  Flag,
  FlagTriangleRight,
  Footprints,
  Gamepad2,
  Gauge,
  GraduationCap,
  Hand,
  House,
  Image,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  Library,
  Lock,
  LogOut,
  Map,
  MapPin,
  Menu,
  Mic,
  Milestone,
  Music,
  Pause,
  PartyPopper,
  Pencil,
  Play,
  Plus,
  Printer,
  RotateCcw,
  ScanLine,
  ScrollText,
  Search,
  Send,
  Shapes,
  Sparkles,
  Speech,
  Square,
  Star,
  Target,
  Trash2,
  Trophy,
  Undo2,
  Upload,
  User,
  UserRound,
  Users,
  Volume2,
  X,
} from 'lucide-angular';

/**
 * The icon set the app draws from. Keeping it explicit (rather than pulling in
 * every Lucide icon) keeps the bundle small and the visual language consistent
 * — one name per idea, used the same way everywhere.
 */
export const APP_ICONS = {
  // Navigation & chrome
  dashboard: LayoutDashboard,
  students: Users,
  books: Library,
  book: BookOpen,
  'book-marked': BookMarked,
  badges: Award,
  trophy: Trophy,
  log: ClipboardList,
  profile: UserRound,
  user: User,
  logout: LogOut,
  menu: Menu,
  map: Map,
  'map-pin': MapPin,
  home: House,
  institution: Landmark,
  buddy: Bird,
  'flag-finish': FlagTriangleRight,

  // Actions
  add: Plus,
  edit: Pencil,
  delete: Trash2,
  upload: Upload,
  scan: ScanLine,
  print: Printer,
  download: Send,
  search: Search,
  close: X,
  back: ChevronLeft,
  forward: ChevronRight,
  undo: Undo2,
  clear: Eraser,
  retry: RotateCcw,
  remove: Delete,

  // Media & speech
  play: Play,
  pause: Pause,
  stop: Square,
  listen: Volume2,
  mic: Mic,
  speech: Speech,
  music: Music,
  image: Image,

  // Learning
  story: FileText,
  game: Gamepad2,
  quiz: Brain,
  shapes: Shapes,
  scroll: ScrollText,
  feather: Feather,
  graduation: GraduationCap,
  milestone: Milestone,
  flag: Flag,
  footprints: Footprints,
  layers: Layers,

  // Status & feedback
  check: Check,
  'check-double': CheckCheck,
  'check-circle': CircleCheck,
  verified: BadgeCheck,
  alert: CircleAlert,
  info: Info,
  help: CircleHelp,
  locked: Lock,
  star: Star,
  crown: Crown,
  target: Target,
  gauge: Gauge,
  sparkles: Sparkles,
  celebrate: PartyPopper,
  wave: Hand,
} as const;

/** Every icon name the app knows about. */
export type IconName = keyof typeof APP_ICONS;

/** Every icon name, for pickers that let a teacher choose one. */
export const ICON_NAMES = Object.keys(APP_ICONS) as IconName[];
